services:
  ntos-server:
    image: test:latest
    #image: dselen/ntos-server:latest
    container_name: ntos-server
    restart: unless-stopped
    ports:
      - 8080:80/tcp
    volumes:
      - ntos_data:/data
volumes:
  ntos_data:
